### ISSUE TITLE
How to cite your work?

### ISSUE THREAD

**Issue by yuedeji** [lorpac/amino_acid_network#1]
Hi There,

This is definitely a great work! It helped me to create the graph from the PDB file. I would like to cite your work in our paper. Do you have a paper or something for us to cite?

Best,
Yuede

**Comment by lorpac** [comment]
Dear Yuede,

Thanks for your feedback and sorry for the late reply. You can cite the following paper:

Dorantes-Gilardi, R., Bourgeat, L., Pacini, L., Vuillon, L., & Lesieur, C. (2018). In proteins, the structural responses of a position to mutation rely on the Goldilocks principle: not too many links, not too few. Physical Chemistry Chemical Physics, 20(39), 25399-25410. 

Lorenza
